CREATE TABLE SLIDES (
  NAME_SLIDE varchar(20),
  LINK_SLIDE varchar(50)
);

CREATE TABLE AUTHORIZES (
  ID_AUTHORIZE VARCHAR(7) PRIMARY KEY,
  AUTHORIZE_NAME VARCHAR(20)
);

CREATE TABLE TASKS (
  ID_TASK varchar(7) PRIMARY KEY,
  TASK_NAME varchar(20)
);

CREATE TABLE PARTICULAR_TASKS (
  ID_TASK varchar(7),
  ID_AUTHORIZE varchar(7)
);

CREATE TABLE USERS (
  ID_USER VARCHAR(7) PRIMARY KEY,
  FULLNAME VARCHAR(50),
  PHONE_NUMBER VARCHAR(10),
  BIRTHDAY date,
  USER_TYPE VARCHAR(20)
);

CREATE TABLE ACCOUNTS (
  ID_ACCOUNT varchar(7),
  ID_AUTHORIZE varchar(7),
  USERNAME VARCHAR(25) UNIQUE,
  PASS_WORD VARCHAR(50),
  STATUS_ACCOUNT INT,
  CREATE_AT DATETIME,
  UPDATE_AT datetime
);

CREATE TABLE CATEGORY (
  ID_CATEGORY VARCHAR(7) PRIMARY KEY,
  CATEGORY_NAME VARCHAR(50)
);

CREATE TABLE MATERIAL (
  ID_MATERIAL VARCHAR(7) PRIMARY KEY,
  MATERIAL_NAME VARCHAR(20)
);

CREATE TABLE PRODUCTS (
  ID_PRODUCT VARCHAR(7) PRIMARY KEY,
  ID_CATEGORY VARCHAR(7),
  ID_MATERIAL VARCHAR(7),
  PRODUCT_NAME VARCHAR(50),
  QUANTITY_SOLD INT,
  CREATE_AT DATETIME,
  UPDATE_AT DATETIME
);

CREATE TABLE PARTICULAR_PRODUCTS (
  ID_PRODUCT VARCHAR(7),
  SIZE INT,
  PRICE FLOAT,
  QUANTITY_REMAIN INT
);

CREATE TABLE PROMOTIONS (
  ID_PROMOTION VARCHAR(7) PRIMARY KEY,
  PROMOTION_NAME VARCHAR(50),
  DISCOUNT_PERCENT FLOAT,
  DATE_START DATETIME,
  DATE_END DATETIME
);

CREATE TABLE PROMOTION_PRODUCTS (
  ID_PROMOTION_PRODUCT VARCHAR(7) PRIMARY KEY,
  ID_PROMOTION VARCHAR(7),
  ID_PRODUCT VARCHAR(7)
);

CREATE TABLE IMAGES (
  ID_PRODUCT VARCHAR(7),
  LINK_IMAGE VARCHAR(50)
);

CREATE TABLE CART (
  ID_CART VARCHAR(7) PRIMARY KEY,
  ID_ACCOUNT VARCHAR(7),
  TOTAL_PRICE_CART FLOAT
);

CREATE TABLE PARTICULAR_CART (
  ID_CART VARCHAR(7),
  ID_PRODUCT VARCHAR(7),
  QUANTITY INT
);

CREATE TABLE BILLS (
  ID_BILL VARCHAR(7) PRIMARY KEY,
  ID_STAFF VARCHAR(7),
  ID_CUSTOMER VARCHAR(7),
  TOTAL_BILL FLOAT,
  DATE_BILL DATETIME,
  STATUS_BILL INT
);

CREATE TABLE PARTICULAR_BILLS (
  ID_BILL VARCHAR(7),
  ID_PRODUCT VARCHAR(7),
  QUANTITY INT
);

CREATE TABLE FEEDBACKS (
  ID_FEEDBACK VARCHAR(7) PRIMARY KEY,
  ID_BILL VARCHAR(7),
  CONTENT VARCHAR(200),
  STAR INT(5),
  DATE_FEEDBACK DATETIME
);

CREATE TABLE RECEIPTS (
  ID_RECEIPT VARCHAR(7) PRIMARY KEY,
  ID_STAFF VARCHAR(7),
  TOTAL_PRICE FLOAT,
  DATE_RECEIPT DATETIME
);

CREATE TABLE PARTICULAR_RECEIPTS (
  ID_RECEIPT VARCHAR(7),
  ID_PRODUCT VARCHAR(7),
  QUANTITY INT,
  PRICE FLOAT
);

CREATE TABLE USER_SHIPPING_ADDRESS (
  ID_USER_SHIPPING_ADDRESS VARCHAR(7) PRIMARY KEY,
  ID_ACCOUNT VARCHAR(7),
  SHIPPING_ADDRESS VARCHAR(100)
);

-- Liên kết khóa ngoại

ALTER TABLE PARTICULAR_TASKS ADD FOREIGN KEY (ID_TASK) REFERENCES TASKS (ID_TASK);

ALTER TABLE PARTICULAR_TASKS ADD FOREIGN KEY (ID_AUTHORIZE) REFERENCES AUTHORIZES (ID_AUTHORIZE);

ALTER TABLE ACCOUNTS ADD FOREIGN KEY (ID_AUTHORIZE) REFERENCES AUTHORIZES (ID_AUTHORIZE);

ALTER TABLE ACCOUNTS ADD FOREIGN KEY (USERNAME) REFERENCES USERS (ID_USER);

ALTER TABLE PRODUCTS ADD FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY (ID_CATEGORY);

ALTER TABLE PRODUCTS ADD FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL);

ALTER TABLE PARTICULAR_PRODUCTS ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT);

ALTER TABLE PROMOTION_PRODUCTS ADD FOREIGN KEY (ID_PROMOTION) REFERENCES PROMOTIONS (ID_PROMOTION);

ALTER TABLE PROMOTION_PRODUCTS ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT);

ALTER TABLE IMAGES ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT);

ALTER TABLE CART ADD FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNTS (ID_ACCOUNT);

ALTER TABLE PARTICULAR_CART ADD FOREIGN KEY (ID_CART) REFERENCES CART (ID_CART);

ALTER TABLE PARTICULAR_CART ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT);

ALTER TABLE BILLS ADD FOREIGN KEY (ID_STAFF) REFERENCES ACCOUNTS (ID_ACCOUNT);

ALTER TABLE BILLS ADD FOREIGN KEY (ID_CUSTOMER) REFERENCES ACCOUNTS (ID_ACCOUNT);

ALTER TABLE PARTICULAR_BILLS ADD FOREIGN KEY (ID_BILL) REFERENCES BILLS (ID_BILL);

ALTER TABLE PARTICULAR_BILLS ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT);

ALTER TABLE FEEDBACKS ADD FOREIGN KEY (ID_BILL) REFERENCES BILLS (ID_BILL);

ALTER TABLE RECEIPTS ADD FOREIGN KEY (ID_STAFF) REFERENCES ACCOUNTS (ID_ACCOUNT);

ALTER TABLE PARTICULAR_RECEIPTS ADD FOREIGN KEY (ID_RECEIPT) REFERENCES RECEIPTS (ID_RECEIPT);

ALTER TABLE PARTICULAR_RECEIPTS ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT);

ALTER TABLE USER_SHIPPING_ADDRESS ADD FOREIGN KEY (ID_ACCOUNT) REFERENCES ACCOUNTS (ID_ACCOUNT);
